api_platform:
    defaults:
        pagination_enabled: false
    mapping:
        paths: [
                "%kernel.project_dir%/src/Entity",
                #  "%kernel.project_dir%/config/api_platform/ressources.yaml",
            ]
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
